//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITSapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detector()
        {
            this.Post = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> MakeDate { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public int DetectorTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
        public virtual DetectorType DetectorType { get; set; }
    }
}
