//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITSapp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class workEntities1 : DbContext
    {
        public workEntities1()
            : base("name=workEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detector> Detector { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<TechProcess> TechProcess { get; set; }
        public virtual DbSet<DetectorType> DetectorTypeSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
    }
}
