//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITSapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public int Station_Id { get; set; }
        public Nullable<int> Num { get; set; }
        public int Detector_Id { get; set; }
        public int TechProcess_Id { get; set; }
    
        public virtual Detector Detector { get; set; }
        public virtual Station Station { get; set; }
        public virtual TechProcess TechProcess { get; set; }
    }
}
