//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DITSapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechProcess()
        {
            this.Post = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> TechProcessDate { get; set; }
        public Nullable<System.DateTime> NextTechProcessDate { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
    }
}
